export {default as Home} from './Home/home'
export {default as Login} from './Login/Login'
export {default as MenuTrueHome} from './MenuTrueHome/Menu'
export {default as Profile} from './Profile/Profile'
export {default as Search} from './Search/Search'
export {default as Signin} from './Signin/Signin'
